// Builds the package.
//
// 1. Generates src/package-info.ts from package.json so that the library can
//    report its own name and version, and src/well-known/services.ts from
//    src/well-known/services.json, the list of well-known SMTP services. Neither
//    can be a JSON import: those need different syntax in ES modules and
//    CommonJS. The JSON file is also copied into dist/ because
//    require('nodemailer/lib/well-known/services.json') is used in the wild.
// 2. Compiles src/ twice with tsc: once as ES modules into dist/esm and once as
//    CommonJS into dist/cjs. Each output directory gets its own package.json
//    that pins the module format.
// 3. Rewrites the CommonJS files that only have a default export so that
//    `require()` keeps returning the exported class or function itself, the
//    same shape the pre-TypeScript CommonJS sources had.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tsc = require.resolve('typescript/bin/tsc');

function quote(value) {
    return "'" + String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

function generatePackageInfo() {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const source =
        [
            '// Generated by scripts/build.js from package.json. Do not edit by hand.',
            '',
            `export const name = ${quote(pkg.name)};`,
            `export const version = ${quote(pkg.version)};`,
            `export const homepage = ${quote(pkg.homepage)};`
        ].join('\n') + '\n';
    writeIfChanged(path.join(root, 'src', 'package-info.ts'), source);
}

function generateWellKnownServices() {
    const services = JSON.parse(fs.readFileSync(path.join(root, 'src', 'well-known', 'services.json'), 'utf8'));
    const source =
        [
            '// Generated by scripts/build.js from services.json. Do not edit by hand.',
            '',
            "import type { WellKnownServiceDefinition } from './index.js';",
            '',
            'export const services: Record<string, WellKnownServiceDefinition> = ' + JSON.stringify(services, null, 4) + ';'
        ].join('\n') + '\n';
    writeIfChanged(path.join(root, 'src', 'well-known', 'services.ts'), source);
}

// Skips the write when the content is already there so that tsc and tsx caches stay warm
function writeIfChanged(target, source) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) {
        fs.writeFileSync(target, source);
    }
}

function generate() {
    generatePackageInfo();
    generateWellKnownServices();
}

function runTsc(project) {
    const result = spawnSync(process.execPath, [tsc, '-p', project], { cwd: root, stdio: 'inherit' });
    if (result.status !== 0) {
        process.exit(result.status || 1);
    }
}

function listFiles(dir, ext) {
    return fs
        .readdirSync(dir, { recursive: true })
        .filter(name => name.endsWith(ext))
        .map(name => path.join(dir, name));
}

// The entry point is the one module that combines a default export with named
// runtime exports. It keeps its named exports, and its default export is made to
// be the exports object itself. Before the TypeScript build `require('nodemailer')`
// had no default export, so `import nodemailer from 'nodemailer'` in a CommonJS
// compiled consumer resolved to the exports object, and a test double installed
// through either import style was seen by the other. Pointing `default` at the
// exports object keeps that. The alias is non-enumerable so that the enumerable
// keys of the module are the three functions, as before.
const ENTRY_POINT_MODULE = 'nodemailer.js';
const ENTRY_POINT_SHIM =
    "Object.defineProperty(exports, 'default', { value: exports, enumerable: false, writable: true, configurable: true });\n";

// tsc emits `exports.default = X` for `export default X`. For modules whose only
// runtime export is the default one, make `require()` return X directly. The
// default export stays reachable as a non-enumerable `.default` property, which
// is what TypeScript and Babel generated `import X from '...'` code reads.
//
// Any other module that has a default export and named runtime exports can not
// get this treatment, so the build fails for one: silently switching `require()`
// from the class to the exports object would break `require('nodemailer/lib/...')`
// callers.
function applyCjsInterop(dir) {
    const namedExport = /\bexports\.(?!default\b)[A-Za-z_$][\w$]*\s*=/;
    const definedExport = /Object\.defineProperty\(exports,\s*"(?!__esModule")/;
    const starExport = /__exportStar\(/;
    const defaultExport = /\bexports\.default\s*=/;

    for (const file of listFiles(dir, '.js')) {
        const source = fs.readFileSync(file, 'utf8');
        if (!defaultExport.test(source)) {
            continue;
        }
        const name = path.relative(dir, file);
        if (name === ENTRY_POINT_MODULE) {
            writePatched(file, source, ENTRY_POINT_SHIM);
            continue;
        }
        if (namedExport.test(source) || definedExport.test(source) || starExport.test(source)) {
            throw new Error(
                name +
                    ' has a default export and named runtime exports. Keep default-export modules default-only ' +
                    '(attach extra values as properties of the exported function or class)'
            );
        }
        const shim =
            'module.exports = exports.default;\n' +
            "Object.defineProperty(module.exports, 'default', { value: exports.default, enumerable: false, writable: true, configurable: true });\n";
        writePatched(file, source, shim);
    }
}

// Appends a shim to a compiled module, ahead of the source map comment if there is one
function writePatched(file, source, shim) {
    const mapComment = source.lastIndexOf('//# sourceMappingURL=');
    const patched = mapComment === -1 ? source + shim : source.slice(0, mapComment) + shim + source.slice(mapComment);
    fs.writeFileSync(file, patched);
}

function build() {
    generate();
    fs.rmSync(path.join(root, 'dist'), { recursive: true, force: true });

    runTsc('tsconfig.esm.json');
    runTsc('tsconfig.cjs.json');

    fs.writeFileSync(path.join(root, 'dist', 'esm', 'package.json'), JSON.stringify({ type: 'module' }, null, 4) + '\n');
    fs.writeFileSync(path.join(root, 'dist', 'cjs', 'package.json'), JSON.stringify({ type: 'commonjs' }, null, 4) + '\n');

    applyCjsInterop(path.join(root, 'dist', 'cjs'));

    fs.mkdirSync(path.join(root, 'dist', 'well-known'), { recursive: true });
    fs.copyFileSync(path.join(root, 'src', 'well-known', 'services.json'), path.join(root, 'dist', 'well-known', 'services.json'));
}

if (process.argv.includes('--generate-only')) {
    generate();
} else {
    build();
}
